### ISSUE TITLE
Character is cloned and randomly warped after moving down

### ISSUE THREAD

**Issue by Corun-Kail** [Amiroslo/PyOT#2]
On OTClient 0.6.6 using protocol 8.6 to connect, ubuntu 16.04. Server is hosted using python3.3 in virtualenv on local server.
When character quickly descents through ladders or stairs, his position gets randomly warped, since that moment character is unable to move(including /a command usage) unless "/t" command is used. During this event server prints out unhandled core exception. This temporarily allows for movement, cloning character in seemingly random position, and after some random amount of time character gets warped again, however this time being stuck is not necessary.
> [UNHANDLED CORE EXCEPTION!]
> Traceback (most recent call last):
>   File "./game/protocols/base.py", line 597, in _handle
>     OPHANDLERS[packetType](self, player, packet)
>   File "./game/protocols/base.py", line 708, in handleWalkNorth
>     self.handleWalk(player, NORTH)
>   File "./game/protocols/base.py", line 765, in handleWalk
>     if not player.move(direction, stopIfLock=True):
>   File "./game/creature_movement.py", line 384, in move
>     oldTile.removeCreature(self)
>   File "./game/map.py", line 200, in removeCreature
>     self.remove(creature)
> ValueError: list.remove(x): x not in list
> ==============================
> 
> Calling lookAt
> 
> 
> [UNHANDLED CORE EXCEPTION!]
> Traceback (most recent call last):
>   File "./game/protocols/base.py", line 597, in _handle
>     OPHANDLERS[packetType](self, player, packet)
>   File "./game/protocols/base.py", line 716, in handleWalkEast
>     self.handleWalk(player, EAST)
>   File "./game/protocols/base.py", line 765, in handleWalk
>     if not player.move(direction, stopIfLock=True):
>   File "./game/creature_movement.py", line 384, in move
>     oldTile.removeCreature(self)
>   File "./game/map.py", line 200, in removeCreature
>     self.remove(creature)
> ValueError: list.remove(x): x not in list
> ==============================
> 
> 
> 
> [UNHANDLED CORE EXCEPTION!]
> Traceback (most recent call last):
>   File "./game/protocols/base.py", line 597, in _handle
>     OPHANDLERS[packetType](self, player, packet)
>   File "./game/protocols/base.py", line 720, in handleWalkWest
>     self.handleWalk(player, WEST)
>   File "./game/protocols/base.py", line 765, in handleWalk
>     if not player.move(direction, stopIfLock=True):
>   File "./game/creature_movement.py", line 384, in move
>     oldTile.removeCreature(self)
>   File "./game/map.py", line 200, in removeCreature
>     self.remove(creature)
> ValueError: list.remove(x): x not in list
> ==============================
> 
> [E 170312 20:59:43 ioloop:633] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f3c65899ef0>, 0, None)
>     Traceback (most recent call last):
>       File "/home/kail/Projects/PyOT/PyOTTest/lib/python3.3/site-packages/tornado/ioloop.py", line 604, in _run_callback
>         ret = callback()
>       File "/home/kail/Projects/PyOT/PyOTTest/lib/python3.3/site-packages/tornado/stack_context.py", line 275, in null_wrapper
>         return fn(*args, **kwargs)
>       File "./game/creature_movement.py", line 232, in handleAutoWalking
>         direction = self.walkPattern.popleft()
>     AttributeError: 'Player' object has no attribute 'popleft'
> 
> 
> [UNHANDLED CORE EXCEPTION!]
> Traceback (most recent call last):
>   File "./game/protocols/base.py", line 597, in _handle
>     OPHANDLERS[packetType](self, player, packet)
>   File "./game/protocols/base.py", line 830, in handleMoveItem
>     player.autoWalk(player)
>   File "./game/creature_movement.py", line 196, in autoWalk
>     self.handleAutoWalking(0, callback)
>   File "./game/creature_movement.py", line 232, in handleAutoWalking
>     direction = self.walkPattern.popleft()
> AttributeError: 'Player' object has no attribute 'popleft'
> ==============================
> 
> 
> 
> [UNHANDLED CORE EXCEPTION!]
> Traceback (most recent call last):
>   File "./game/protocols/base.py", line 597, in _handle
>     OPHANDLERS[packetType](self, player, packet)
>   File "./game/protocols/base.py", line 830, in handleMoveItem
>     player.autoWalk(player)
>   File "./game/creature_movement.py", line 196, in autoWalk
>     self.handleAutoWalking(0, callback)
>   File "./game/creature_movement.py", line 232, in handleAutoWalking
>     direction = self.walkPattern.popleft()
> AttributeError: 'Player' object has no attribute 'popleft'
> ==============================
> 
examples of clones
![screenshot from 2017-03-12 21-00-15](https://cloud.githubusercontent.com/assets/2961507/23835461/1d025ec0-0768-11e7-9e7e-4de6f4b084e1.png)
some clones still read player direction.
![screenshot from 2017-03-12 21-00-51](https://cloud.githubusercontent.com/assets/2961507/23835463/1d42d1a8-0768-11e7-9c95-8bf38a4fd577.png)
![screenshot from 2017-03-12 21-01-03](https://cloud.githubusercontent.com/assets/2961507/23835462/1d4076ce-0768-11e7-88ce-b3fccd69e585.png)

**Comment by Corun-Kail** [comment]
While I did not tested it personally yamaken93 replicated bug on tibia client 8.6:

![obraz](https://cloud.githubusercontent.com/assets/2961507/23836924/24fc3a8e-0780-11e7-8c89-28edea95a351.png)
![obraz](https://cloud.githubusercontent.com/assets/2961507/23836928/27efa6a4-0780-11e7-923d-d23b4a227616.png)
![obraz](https://cloud.githubusercontent.com/assets/2961507/23836929/2a5b91c8-0780-11e7-91d5-d2e7868b9395.png)
